name:                connect4
version:             0.1.0.0
github:              "Max-Wraith-Whiting/connect4"
license:             BSD-3-Clause
author:              "Max Wraith-Whiting"
maintainer:          "Max.Wraith-Whiting@protonmail.com"
copyright:           "2023 Max Wraith-Whiting"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Max-Wraith-Whiting/connect4#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- optparse-applicative

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  connect4-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - connect4
    - gloss

tests:
  connect4-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - connect4
